# vim: si:ts=2:sts=2:sw=2
# This is a basic workflow to help you get started with Actions

name: Create Deployment

# Controls when the action will run. Triggers the workflow on workflow dispatch
# events
on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "create"
  create:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Create deployment
      uses: maxkomarychev/oction-create-deployment@v0.7.1
      with:
        token: ${{ secrets.DEPLOY_TOKEN }}
        ref: ${{ github.event.inputs.branch }}
        environment: ${{ github.event.inputs.branch }}
