# vim: si:ts=2:sts=2:sw=2
# This is a basic workflow to help you get started with Actions

name: Deploy website

# Controls when the action will run. Triggers the workflow on deployment events
on: deployment

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Update deployment status (in_progress)
      uses: maxkomarychev/oction-create-deployment-status@v0.7.1
      with:
        token: ${{ secrets.DEPLOY_TOKEN }}
        deployment_id: ${{ github.event.deployment.id }}
        state: in_progress

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: actions/checkout@v2
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.deployment.sha }}

    - name: actions/cache@v2 for npm
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: actions/cache@v2 for pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - uses: actions/setup-python@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
        working-directory: public
        bundler-cache: true

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
        export NPM_CONFIG_USERCONFIG=.npmrc
        npm config set audit false
        npm config set fund false
        npm config set loglevel error
        npm config set optional false
        npm config set prefer-offline true

    - name: Build website
      working-directory: public
      run: |
        echo "url: \"https://${{ github.event.deployment.environment }}.svlifeactivation.com\"" >> _config.yml
        JEKYLL_ENV=${{ github.event.deployment.environment }} bundler exec jekyll build -d ../_site

    - name: Build workers site
      run: |
        python $GITHUB_WORKSPACE/scripts/build_site.py built
        cd built
        python $GITHUB_WORKSPACE/scripts/add_environment.py ${{ github.event.deployment.environment }}

    - name: Publish website
      uses: cloudflare/wrangler-action@1.2.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        workingDirectory: built
        environment: ${{ github.event.deployment.environment }}

    - name: Update deployment status (success)
      uses: maxkomarychev/oction-create-deployment-status@v0.7.1
      with:
        token: ${{ secrets.DEPLOY_TOKEN }}
        deployment_id: ${{ github.event.deployment.id }}
        state: success
        environment_url: https://${{ github.event.deployment.environment }}.svlifeactivation.com

    - name: Update deployment status (failure)
      if: failure()
      uses: maxkomarychev/oction-create-deployment-status@v0.7.1
      with:
        token: ${{ secrets.DEPLOY_TOKEN }}
        deployment_id: ${{ github.event.deployment.id }}
        state: failure
